print("Hello World! version 1.04 for hotfix")
print("(C)2018 euntae")
print("Hello!")
print("Hi World!")
print("this program is TEST PROGRAM for master.")
print("Nyang Cat")
print("Cat Cat Comminist")
print("#include <stdio.h>")
print("int main(int argc, char **argv)")
print("{")
print('printf("Hello world!\\n");')
print("return 0;")
print("}")
