print("Hello World! version 1.04a for hotfix")
print("(C)2018 euntae")
print("Hello!")
print("Hi World!")
print("this program is TEST PROGRAM!")
print("#include <stdio.h>")
print("int main(int argc, char **argv)")
print("{")
print('printf("Hello world!\\n");')
print("return 0;")
print("}")
